package de.onecode.navigator.runtime

import androidx.compose.runtime.ProvidableCompositionLocal
import androidx.navigation.NavHostController

lateinit var LocalNavHostController: ProvidableCompositionLocal<NavHostController>