[versions]
compose-navigator = "1.0.2-SNAPSHOT"
android-sdk-min = "21"
android-sdk-target = "34"

java = "17"
kotlin = "1.9.22"

android-plugin = "8.2.2"
compose-bom = "2024.01.00"
compose-navigation = "2.7.6"
compose-compiler = "1.5.8"
android-core = "1.12.0"
android-lifecycle-runtime = "2.7.0"
android-activity-compose = "1.8.2"

ksp = "1.9.22-1.0.16"
kotlinpoet = "1.14.2"

[libraries]
android-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "android-core" }
android-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "android-lifecycle-runtime" }
android-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "android-activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet" }



[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
