name: Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build test
      - name: Upload API
        uses: actions/upload-artifact@v1
        with:
          name: compass-api
          path: compass/api/build/libs/compass-api.jar
      - name: Upload Runtime
        uses: actions/upload-artifact@v1
        with:
          name: compass-runtime
          path: compass/runtime/build/outputs/aar/compass-runtime-release.aar
      - name: Upload KSP
        uses: actions/upload-artifact@v1
        with:
          name: compass-ksp
          path: compass/ksp/build/libs/compass-ksp.jar
