name: Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload API
        uses: actions/upload-artifact@v1
        with:
          name: compose-navigator-api
          path: compose-navigator-api/build/libs/compose-navigator-api.jar
      - name: Upload Runtime
        uses: actions/upload-artifact@v1
        with:
          name: compose-navigator-runtime
          path: compose-navigator-runtime/build/outputs/aar/compose-navigator-runtime-release.aar
      - name: Upload KSP
        uses: actions/upload-artifact@v1
        with:
          name: compose-navigator-ksp
          path: compose-navigator-ksp/build/libs/compose-navigator-ksp.jar
